version: 0.2

env:
    variables:
        S3_BUCKET: "uacap-timescape"
        BUILD_ENV : "nonprod"

phases:
    install:
        commands:
          - sudo apt-get update -y
          - echo Installing source NPM dependencies...
          - npm install

    build:
        commands:
        # Builds Angular application. You can also build using custom environment here like mock or staging
        - echo Build started on `date`
        - npm run build --${BUILD_ENV}

    post_build:
        commands:
        # Clear S3 bucket.
        # Clear S3 bucket.
        - aws s3 rm s3://${S3_BUCKET} --recursive
        - echo S3 bucket is cleared.
        # Copy dist folder to S3 bucket
        - aws s3 cp . s3://${S3_BUCKET} --recursive
        - echo Build completed on `date`

artifacts:
    files:
        - '**/*'
    discard-paths: yes
    base-directory: 'dist*'


