version: 0.2

env:
    variables:
        S3_BUCKET: "uacap-timescape"
        BUILD_ENV : "nonprod"

phases:
    install:
        commands:
          - sudo apt-get update -y
          - echo Installing source NPM dependencies...
          - npm install

    build:
        commands:
        # Builds Angular application. You can also build using custom environment here like mock or staging
        - cd $CODEBUILD_SRC_DIR
        - echo Build started on `date`
        - npm run build --${BUILD_ENV}


artifacts:
  files:
    - '**/*'
  base-directory: $CODEBUILD_SRC_DIR/public/
  discard-paths: no
